CC=gcc

EXEC = check-endian printpid reading x y gtotd touch_bad_memory divbyzero address sig mmap1 showlim


all: $(EXEC)

clean:
	rm -f a.out *.o $(EXEC)

clean-objs:
	rm -f *.o

help:
	echo all-execs/ all-objs /all /clean-all
